/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GWCNFT } from "./GWCNFT";
export type { GWCToken } from "./GWCToken";
export type { Marketplace } from "./Marketplace";
export type { WorkoutRewards } from "./WorkoutRewards";
