/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GWCToken__factory } from "./GWCToken__factory";
export { WorkoutRewards__factory } from "./WorkoutRewards__factory";
